### PR TITLE
Add GitHub Actions workflows

### PR DESCRIPTION
**Pull request by LukeShortCloud**

### CODE REVIEW

**Comment by LukeShortCloud** [comment]
I've ran into some issues using GitHub Actions as I was intending. All of that information has been documented here: https://github.com/LukeShortCloud/rpm-specs-gaming/issues/3#issuecomment-1529116107

**Comment by LukeShortCloud** [comment]
Here's my thought process on the workflows:

* "all.yml" workflow = Build and install every RPM system package.
* "`<PACKAGE>`.yml" workflow = Build the source RPM and upload it to Fedora Copr. There it will automatically build and host the package. A separate workflow is created for each package. If (1) any changes to files in that directory are detected and (2) the change is merged into the "main" branch then this workflow will run.

**Comment by LukeShortCloud** [comment]
This is finally ready for a final review!

There are two primary goals here:

1. Ensure that packages are built successfully.
2. For the main branch, automatically publish updated RPMs to the Fedora Copr where they will be hosted.

There are 3 workflows I created:

- all.yml = Build all RPMs. Runs on non-main branches.
- gamescope-session.yml = Runs on main branch only. If there is a change in the "gamescope-session/" directory, this builds all RPMs. Then it uploads the gamescope-session source RPM to Fedora Copr where it is built into a single binary RPM and is hosted online.
- mesa.yml = Runs on main branch only. If there is a change in the "mesa/", this builds all RPMs. Then it uploads the mesa source RPM to Fedora Copr where it is built into many binary RPMs and is hosted online.

I have proved that the works for uploading to the Fedora Copr:

- gamescope-session = https://github.com/LukeShortCloud/rpm-specs-gaming/actions/runs/4876863335
    - I actually updated the version here as part of this PR. The package and program is working as intended.
- mesa = https://github.com/LukeShortCloud/rpm-specs-gaming/actions/runs/4877148491
   - I added a newline character as updating this package is a lot more complicated and time consuming. This was enough to trigger a build. The packages and programs are working as intended.

These binary RPM packages can be seen here: https://copr.fedorainfracloud.org/coprs/ekultails/gaming/packages/

**Review by yuushazen — APPROVED** [review]
LGTM

**Comment by LukeShortCloud** [comment]
Thanks! I merged this PR and changed the default branch back from "github_actions" to "main" (I needed it at one point to test `on.workflow_run`).

**Pull request merged**
